language: r
pandoc_version: 1.19.2.1

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

before_install:
  - sudo apt-get install libgit2-dev

r_github_packages:
  - stefano-meschiari/latex2exp
  - rorynolan/brownded


before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: _book
