language: r
pandoc_version: 1.19.2.1

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

r_github_packages:
  - stefano-meschiari/latex2exp
  - rorynolan/brownded


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh