# Instrumentation and Software {#instrumentation-and-software}


## Instrumentation 

All of the images used in this thesis were acquired on a Leica SP8 confocal microscope.^[https://www.leica-microsystems.com/products/confocal-microscopes/details/product/leica-tcs-sp8] Importantly, the detectors that we have on this microscope are capable of photon counting. 

These images were acquired by Luis Alvarez (postdoctoral researcher), Maro Iliopoulou (research assistant) and Sergi Padilla-Parra (supervisor).



## Software programs, languages and tools


### C++

_C++_ [@cpp] is a genaral-purpose programming language optimized for performance (speed), efficiency (with use of computer resources) and flexibility.^[https://en.wikipedia.org/wiki/C%2B%2B] I used it for its speed, since many of the algorithms that I developed were quite computationally intensive and hence speed was an important issue.


### R 

_R_ [@R] is a programming language and free software environment for statistical computing and graphics.^[https://en.wikipedia.org/wiki/R_(programming_language)] I use R primarily as a wrapper for my C++ code to make my algorithms more user-friendly. R is best used with the RStudio integrated development environment. 


### ImageJ

_ImageJ_ [ImageJ] is an open source image processing program designed for scientific multidimensional images.^[https://imagej.net] It is the preferred image viewing and analysis software in the community. I have written my software in C++ and R because they are easier for developers, but I still intend to translate my image-related algorithms ImageJ plugins. ImageJ is best used via the FIJI [@FIJI] distribution.^[https://imagej.net/Fiji]


### Git and GitHub

Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.^[https://git-scm.com/] GitHub is a web-based hosting service for version control using Git.^[https://en.wikipedia.org/wiki/GitHub] All of the computer code used during my thesis can be found on my GitHub at https://github.com/rorynolan. The vast majority of my time during my thesis was spent writing code so this GitHub account is the best record of the work that I have done.


### My software packages