# Applications {#applications}


## Dimerization of FKBP12

Myristoylated FKBP12 is known to dimerize upon addition of the drug AP1510 [@Amara]. As a test application of exponential smoothing detrending (section \@ref(exponential-smoothing-detrending)) with automatically chosen parameter $\tau$, we used it with number and brightness to verify this dimerization. We tested this in 20 Cos7 cells with mClover-labelled FKBP12. We found a brightness increase in $\epsilon$ of $\approx 1.6$-fold using the _automatic_ detrending method. The naiive choice of $\tau=10$ resulted in a $\approx 0.7$-fold calculated increase, which is indeed a decrease. The $\approx 1.6$-fold increase suggests that dimerization had occurred, however, we expected the increase to be $\approx 2$-fold upon dimerization. In that publication [@nandb], we postulated that the 1.6 figure was due to the fact that not all of the protein had dimerized. Recently, a paper came out [@fpcompare] explaining how the assumption that all fluorophores emit signal is invalid and that because of this, oligomeric state changes calculated from brightness must be adjusted by a correction factor specific to the fluorophore. Unfortunately, this study did not characterize mClover, so we do not know its correction factor. I suspect that applying this correction would bring our figure of 1.6 a lot closer to 2. The fact that the naive choice of $\tau=10$ gave a decrease in brightness shows that arbitrary parameter choices lead to unpredictable and unreliable results and should hence be avoided.


## Example two
