# Discussion


## Fluorescence fluctuation spectroscopy

Even with photon-counting detectors, FFS is a difficult technique. There are many pitfalls: the acquisition settings (dwell time and frame rate) must be correct and the correct settings for these parameters depend on the residence time $\tau_D$ of the protein of interest, which is non-trivial to measure. The acquired data must be checked to ensure there is not an excess of photobleaching and if there is not, there will inevitably still be some bleaching, so this must be corrected for. Until now, it was practically impossible to perform this correction correctly, because all methods required the user to select a vital correction parameter ($\tau$ or $l$) without providing any instructions as to how the parameter should be chosen. I have now solved this problem such that now image series can be safely detrended by novice users, as this parameter is chosen for them in the background. Now, detrending an image `img.tif` with the _Robin Hood_ method is as simple as typing the command `img_detrend_rh("img.tif")` in my software. This should make FFS techniques safer and easier to use, opening FFS techniques up to more users, however the expertise required is still such that FFS may struggle to expand from the domain of microscopy and biophysics into a more commonly used biological technique. 


## The evolution of detrending algorithms

Previously, FFS detrending methods were based on smoothing methods taken from the field of time-series analysis. The fact that these smoothing methods required a choice of smoothing parameter was ignored by sticking to the arbitrary choice of $l=10$ for this parameter. 

My work in investigating the significance of this smoothing parameter found that this arbitrary choice was totally incorrect. The use of simulated image series and the fact that immobile particles have brightness $B=1$ opened up a means of solving for the correct choice of this parameter without the need for user input. This was the first set of _automatic detrending_ methods, whereby to detrend, the users task was a simple as clicking a `detrend` button. 

Still, using smoothing approaches to detrend low-intensity data is problematic because it involves approximating very discrete time series with continuous functions; this is unwise and unnecessary. The _Robin Hood_ idea of giving photon counts directly from one pixel to another in an image series circumvents the need for smoothing. The detrending process can be simplified from $\mathbb{N}_0 \rightarrow \mathbb{R} \rightarrow \mathbb{N}_0$ to $\mathbb{N}_0 \rightarrow \mathbb{N}_0$. Conveniently, the automatic approach used in the smoothing approaches to detrending can readily be extended to _Robin Hood_ detrending. 

There are no obvious caveats to the _Robin Hood_ bleaching correction method and thus no more work is needed on its theory. However, it is vital to bear in mind that one should always try to avoid the source of error in the first place rather than rely on correction methods. 


## Applications of the new detrending techniques


### FKBP

The FKBP applications of these detrending techniques in Cos-7 cells [@nandb] and in-vitro were mainly to demonstrate that N&B used with these detrending techniques is a reliable method to measure oligomerization. The in vitro study [@JOVE] was particularly interesting because it was the first in vitro application of number and brightness.


### HIV-1 receptor stoichiometry

The study of HIV-1 receptor stoichiometry [@HIVstoichiometry] is a _real-life_ application of N&B and ccN&B, made possible by the automatic detrending algorithm. We have shown that this kind of fine-grained information about the process of HIV-1 fusion can be measured on a temporal basis in live cells. Whilst this alone is very exciting, it paves the way for similar studies to be done with HIV-1 and different cell types and indeed for other virus fusion processes to be probed in this way. 


### Multiplexing with structural biology

Our collaboration with structural biologists [@HIVstoichiometry] is a demonstration of how live cell fluorescence microscopy and structural biology can be coplementary. The sub-molecular insight from structural biology is not available from live cell fluorescence microscopy, while the dynamic information from live cell fluorescence microscopy cannot be gotten from structural biology.


### Fluorescence fluctuation spectroscopy

FFS has many applications. Indeed the original N&B paper [@NB] alone has over 250 citations. All of these and future FFS studies require correct detrending to be reliable. _Robin Hood_ detrending is the answer for this. A major challenge will be making _Robin Hood_ visible, available and easy to use for the community. This means that the algorithm must be peer-reviewed, made available in all of the major free imaging softwares (ImageJ, python, R) and very well documented: a good manual is essential with any software package. 