# Future plans


## Translate software to _ImageJ_

Whilst I really like R, the fluorescence community does not use it, which has been a major barrier to the use of my algorithms by others. I will code my detrending algorithms as _ImageJ_ plugins and also as python modules so that more of the community have easy access to them.


## Study real data bleaching profiles with simulations {#mimic}

It was mentioned in section \@ref(detrend-compare) that it would be possible to study the effect of real bleaching as opposed to simulated ideal bleaching and why it is more necessary to detrend in the real data case, by mimicking real bleaching profiles with simulations. This is something I would like to do. It would be difficult because it would require the collection and cataloging of a diverse set of real data bleaching profiles from various biological samples. This would be the bottleneck because I have already written the simulation and analysis pipelines. 


## Robin Hood publication

Once _Robin Hood_ has been implemented in _ImageJ_ and more realistic bleaching problems have been studied, _Robin Hood_ should be published.


## Revisit old N&B data with new detrending algorithm

Having claimed that Robin Hood detrending is significantly better than previous detrending methods, it makes sense to revisit old results found using old detrending methods to see how much they would be changed with the application of this new detrending algorithm. The main difficulty in such a project would be obtaining the old data. To this day, most microscopy publications do not have their associated images in a centralised repository, so the only way to get this data is to request it from the authors.


## Compare FRET with FCS

I have the idea that when the question "Do these proteins interact?" is answered by Forster resonance energy transfer (FRET, @Frster), it should also be answerable by FCS. I would like to try to reproduce some standard FRET results with FCS. I am particularly interested to find out if there are instances where one technique succeeds in detecting interaction and the other fails, and why this might be. For example, it might be possible that for a given interacting pair of proteins, it is impossible to label them such that the FRET couple is close enough for FRET to be detected, but that this interaction is detectable by FCS. These techniques have been compared before [@Sahoo], but not by trying to reproduce previous work. In addition, attempts by new groups to reproduce work that is accepted in the literature are always interesting [@Baker2016]. 

