--- 
title: "Algorithms for the Correction of Photobleaching"
author: "Rory Nolan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib, papers.bib]
biblio-style: apalike
link-citations: yes
fontsize: 12pt
geometry: margin=35mm
linkcolor: blue
citecolor: green
urlcolor: NavyBlue
toccolor: blue
linestretch: 2
description: "Rory Nolan's PhD thesis"
---

```{r load-pkgs, include=FALSE}
# The dev version of latex2exp is needed
pkgs <- c("tidyverse", "forcats", "magrittr", "ijtiff", "cranlogs", "lubridate",
          "curl", "detrendr", "nandb", "filesstrings", "knitr", "latex2exp",
          "janitor", "RcppRoll", "abind", "brownded", "here")
lapply(pkgs, library, character.only = TRUE)

knitr::opts_chunk$set(comment = "#>", fig.asp = 0.6, 
                      out.width = "100%", fig.align = "left",
                      message = FALSE)

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

roll_mean_n_by_nofill <- function(x, n_by) {
  roll_mean(x, n = n_by, by = n_by) %>% 
    {.[seq_along(.) %% n_by == 1]}
}

move_to_groups_folder <- function() {
  groups_theses_path <- str_c("/Volumes/groups/cellular-imaging/",
                              "ReadingList/Theses/Rory")
  if (dir.exists(groups_theses_path)) {
    file.copy(here("_book", "phdthesis.pdf"), groups_theses_path)
    message("success")
  } else {
    message("failure")
  }
}
```


# Preface {-}


## Ways to read {-}

In my opinion, the best way to read this thesis is on the web at https://rorynolan.github.io/phdthesis/. If you are reading this on the web now but would like a pdf version, click on the download symbol at the top left of the page (to the right of the __A__) and select PDF.


## Apportion of credit {-}

Whilst I have attempted to make it clear throughout what I myself did and did not do in relation to all work mentioned, for clarity I include the following rules of thumb:

* The idea for fluorescence fluctuation spectroscopy (FFS) as the main area of my thesis was Sergi Padilla-Parra's.
* Molecular biology was done by Maro Iliopoulou and Luis Alvarez.
* Imaging was done by Maro Iliopoulou, Luis Alvarez and Sergi Padilla-Parra.
* The idea that correction for bleaching was the crucial step for FFS analysis was formulated by Luis Alvarez, Sergi Padilla-Parra and I.
* I formulated the solutions for how to correctly correct for bleaching, i.e. the automatic parameter choice and the Robin Hood algorithm.
* I wrote all of the software and maintain all of it.
* All FFS analysis was performed using my software. The software was used to analyse data by Maro Iliopoulou, Luis Alvarez, Sergi Padilla Parra and I. 
* On all papers where I am the first listed author, I wrote the paper, taking suggested amendments from other listed authors. The NSMB paper [@HIVstoichiometry] was written by Maro and Sergi; I also made significant contributions to the writing of that manuscript but my main role in that project was in data analysis. In all other papers where I am listed as an author, my role was minor.

Sergi Padilla-Parra is my supervisor. Luis Alvarez is a postdoctoral researcher in Sergi's group and Maro Iliopoulou is a research assistant in Sergi's group.  


## Publications {-}

#### First author {-}

* R. Nolan and S. Padilla-Parra. "filesstrings: An R package for file and
string manipulation". In: _Journal of Open Source Software_ 2.14 (2017).
* R. Nolan and S. Padilla-Parra. "exampletestr—An easy start to unit
testing R packages". In: _Wellcome open research_ 2 (2017).
* R. Nolan, L. Alvarez, J. Elegheert, et al. "nandb—number and brightness
in R with a novel automic detrending algorithm". In: _Bioinformatics_ 33.21
(2017).
* R. Nolan, M. Iliopoulou, L. Alvarez, et al. "Detecting protein
aggregation and interactions in live cells: a guide to Number and
Brightness". In: _Methods_ (2017).
* R. Nolan and S. Padilla-Parra. "ijtiff: An R package providing TIFF I/O
for ImageJ users". In: _Journal of Open Source Software_ 3.23 (2018).
* R. Nolan, L. Alvarez, S. C. Griffiths, et al. “Calibration-Free In-Vitro
Quantification of Protein Homo-Oligomerization Using Commercial
Instrumentation and Free, Open Source Brightness Analysis Software”. In:
_Journal of Visualized Experiments_ 0.0 (2018).

#### Co-first author {-}

* M. Iliopoulou, R. Nolan, L. Alvarez, et al. "A dynamic three step
mechanism drives the HIV-1 prefusion reaction". In: _Nat. Struct. Mol. Biol._
0.0 (2018).

#### Other {-}

* D. M. Jones, L. A. Alvarez, R. Nolan, et al. “Dynamin-2 stabilizes the
HIV-1 fusion pore with a low oligomeric state”. In: _Cell reports_ 18.2
(2017).
* G. M. Jakobsdottir, M. Iliopoulou, R. Nolan, et al. "On the whereabouts
of HIV-1 cellular entry and its fusion ports". In: _Trends in molecular
medicine_ (2017).
* Q. F. Wills, E. Mellado-Gomez, R. Nolan, et al. "The nature and nurture
of cell heterogeneity: accounting for macrophage gene-environment
interactions with single-cell RNA-Seq". In: _BMC genomics_ 18.1 (2017).