library(brownded)
library(ijtiff)
set.seed(1)
sim1 <- bbm_simulate(1e5, 100, c(64, 64), end_time = 499)
bleach_rate1 <- bleach_fraction_to_rate(0.15, length(unique(sim1$t)))
sim1_bleached <- bbm_bleach_simulation(sim1, bleach_rate1)
img1 <- bbm_simulation_to_img(sim1, 1, "p", 4)
dir.create("img")
write_tif(img1, here("img", "sim1"))
img1_bleached <- bbm_simulation_to_img(sim1_bleached, 1, "p", 4)
write_tif(img1_bleached, here("img", "sim1_bleached"))
rm(sim1, sim1_bleached)
sim2 <- bbm_simulate(1e5, 100, c(64, 64), end_time = 499)
bleach_rate2 <- bleach_fraction_to_rate(0.20, length(unique(sim2$t)))
sim2_bleached <- bbm_bleach_simulation(sim2, bleach_rate2)
img2 <- bbm_simulation_to_img(sim2, 1, "p", 7)
write_tif(img2, here("img", "sim2"))
img2_bleached <- bbm_simulation_to_img(sim2_bleached, 1, "p", 7)
write_tif(img2_bleached, here("img", "sim2_bleached"))
rm(sim2, sim2_bleached)
